apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
  labels:
    app: spring-boot-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8s-deployment
  template:
    metadata:
      name: spring-boot-k8s-deployment
      labels:
        app: spring-boot-k8s-deployment
    spec:
      containers:
        - name: spring-boot-k8s
          image: utsamatech/utsama-devops-integration
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8ssvc
  labels:
    app: spring-boot-k8s-deployment
spec:
    selector:
        app: spring-boot-k8s-deployment
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: NodePort
      